<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        \App\Models\User::factory()->create();

        $user = \App\Models\User::first();

        \App\Models\Projet::insert([
            [
                'user_id' => $user->id,
                'titre' => 'MonTerrain',
                'description' => 'Plateforme de réservation de terrains de sport avec calendrier FullCalendar, système de paiement, confirmation/annulation des réservations, personnalisation du curseur et panneau d\'administration.',
                'image' => null,
                'lien' => 'https://monterrain.onrender.com',
                'github' => 'https://github.com/papechk/monterrain',
                'tags' => json_encode(['Laravel', 'Breeze', 'FullCalendar', 'Tailwind']),
                'ordre' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'SignalementUrbain',
                'description' => 'Plateforme de signalement urbain avec carte interactive Leaflet style Waze, gestion des catégories de signalements, réservation de terrains, système de paiement et tableau de bord.',
                'image' => null,
                'lien' => 'https://signalementurbain.onrender.com',
                'github' => 'https://github.com/papechk/SignalementUrbain',
                'tags' => json_encode(['Laravel', 'Leaflet.js', 'Tailwind', 'PHP']),
                'ordre' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'SunuTontine',
                'description' => 'Application de gestion de tontines avec CRUD tontines et membres, suivi des cotisations, calendrier FullCalendar, rôles gestionnaire/participant et tableau de bord par rôle.',
                'image' => null,
                'lien' => 'https://sunutontine.onrender.com',
                'github' => 'https://github.com/papechk/sunuTontine',
                'tags' => json_encode(['Laravel', 'Breeze', 'FullCalendar', 'Tailwind']),
                'ordre' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'GStockBoncoin',
                'description' => 'Système de gestion de stock et point de vente : boutiques, catégories, produits, clients, ventes avec lignes de vente, mouvements de stock, dépenses et résumés journaliers.',
                'image' => null,
                'lien' => 'https://gstockboncoin.onrender.com',
                'github' => 'https://github.com/papechk/gStockBoncoin',
                'tags' => json_encode(['Laravel', 'Breeze', 'MySQL', 'Tailwind']),
                'ordre' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'PapiGPT',
                'description' => 'Application Laravel de génération de documents avec 5 designs, templates personnalisables et export PDF/Word. Déployée sur Render.',
                'image' => null,
                'lien' => 'https://papigpt.onrender.com',
                'github' => 'https://github.com/papechk/papigpt',
                'tags' => json_encode(['Laravel', 'Blade', 'PHP', 'Render']),
                'ordre' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'GestionSalaire',
                'description' => 'Application de gestion des salaires avec départements, employés, calcul et suivi des salaires, authentification et tableau de bord.',
                'image' => null,
                'lien' => 'https://gestionsalaire.onrender.com',
                'github' => 'https://github.com/papechk/gestionSalaire',
                'tags' => json_encode(['Laravel', 'Breeze', 'MySQL', 'Tailwind']),
                'ordre' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'TestImo',
                'description' => 'Application d\'annonces immobilières avec gestion de propriétés, système de tags, panneau d\'administration et page d\'accueil vitrine.',
                'image' => null,
                'lien' => 'https://testimo.onrender.com',
                'github' => 'https://github.com/papechk/testImo',
                'tags' => json_encode(['Laravel', 'Breeze', 'MySQL', 'Tailwind']),
                'ordre' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Quiz Interactif',
                'description' => 'Application de quiz interactive avec catégories Linux, Oracle, Python, Windows Server et Admission Sherbrooke. Suivi des scores via Supabase, mini-cours intégrés et interface responsive.',
                'image' => null,
                'lien' => 'https://pkeinde6.github.io/quiz-app',
                'github' => 'https://github.com/Pkeinde6/quiz-app',
                'tags' => json_encode(['Vue.js', 'Tailwind', 'Supabase']),
                'ordre' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Gestion Cahier de Textes',
                'description' => 'Application desktop WinForms de gestion de cahier de textes scolaire : classes, départements, matières, professeurs, séances, devoirs, emplois du temps et syllabus avec Entity Framework.',
                'image' => null,
                'lien' => 'https://github.com/papechk/GestionCahierTexte/releases/tag/v1.0.0',
                'github' => 'https://github.com/papechk/GestionCahierTexte',
                'tags' => json_encode(['C#', '.NET', 'WinForms', 'Entity Framework', 'SQL Server']),
                'ordre' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Gestion Scolaire',
                'description' => 'Application desktop de gestion d\'établissement scolaire : inscription élèves, gestion des classes, saisie de notes, emplois du temps et génération de bulletins.',
                'image' => null,
                'lien' => 'https://github.com/papechk/GestionCahierTexte/releases/tag/v1.0.0',
                'github' => 'https://github.com/Pkeinde6/gestionEcole',
                'tags' => json_encode(['C#', '.NET', 'WinForms', 'SQL Server']),
                'ordre' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Portfolio Dynamique',
                'description' => 'Site portfolio avec animations GSAP avancées, scroll-driven transitions en 9 phases, effet WebGL sur images et gestion de contenu Laravel.',
                'image' => null,
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/portfolio-with-adminPanel',
                'tags' => json_encode(['Laravel', 'Tailwind', 'GSAP', 'WebGL']),
                'ordre' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'To-Do List',
                'description' => 'Application de gestion de tâches avec Vue 3 Composition API : ajout, suppression, filtrage (toutes/actives/terminées) et persistance via localStorage.',
                'image' => null,
                'lien' => 'https://pkeinde6.github.io/todo-list/',
                'github' => 'https://github.com/Pkeinde6/todo-list',
                'tags' => json_encode(['Vue.js', 'Vite', 'CSS']),
                'ordre' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Système Bancaire',
                'description' => 'Système bancaire orienté objet en Java avec gestion de comptes courants, comptes épargne, dépôts et retraits.',
                'image' => null,
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/java-banking-system',
                'tags' => json_encode(['Java', 'POO']),
                'ordre' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Star Group',
                'description' => 'Site vitrine multi-pages pour l\'entreprise Star Group avec accueil, services, à propos et contact.',
                'image' => null,
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/Star-group',
                'tags' => json_encode(['PHP', 'CSS', 'JavaScript']),
                'ordre' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Tic Tac Toe',
                'description' => 'Jeu de morpion classique développé en Python (CLI) et en Vue.js (web), avec détection automatique des victoires et matchs nuls.',
                'image' => null,
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/tic-tac-toe',
                'tags' => json_encode(['Python', 'Vue.js']),
                'ordre' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Projets .NET',
                'description' => 'Collection de projets console et desktop en C# .NET : calculatrices, algorithmes (Armstrong, nombres premiers, Euclide, méthode égyptienne), équations du second degré.',
                'image' => null,
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/dotnet-projects',
                'tags' => json_encode(['C#', '.NET']),
                'ordre' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Projets Python',
                'description' => 'Exercices et projets Python : jeu de devinette, cryptographie, convertisseur, manipulation de listes et fonctions.',
                'image' => null,
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/python-projects',
                'tags' => json_encode(['Python']),
                'ordre' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
