<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $user = \App\Models\User::create([
            'nom' => 'Cheikh Keinde',
            'slogan' => 'Full-Stack Developer',
            'description' => 'Développeur fullstack basé à Dakar. Laravel, Vue.js, C#/.NET, Python, Java.',
            'photo' => 'default-avatar.jpg',
            'tel1' => '772756581',
            'tel2' => '+1(438) 465-8983',
            'email' => 'pkeinde6@gmail.com',
            'password' => 'password',
            'adresse' => 'Dakar, Sénégal',
            'poste' => 'Full-Stack Developer',
            'link' => 'https://github.com/papechk',
            'role' => 'superadmin',
        ]);

        \App\Models\Projet::insert([
            [
                'user_id' => $user->id,
                'titre' => 'Yoonu Jigeen',
                'description' => 'Application bilingue (français/wolof) d\'intermédiation en santé féminine. Les patientes recherchent des gynécologues, demandent des rendez-vous et suivent leur parcours. 25+ API REST sécurisées, espaces patient/gynécologue/admin, chatbot texte/audio, notifications et suivi opérationnel.',
                'image' => 'images/projets/portfolio-dynamique.png',
                'lien' => null,
                'github' => 'https://github.com/papekeinde/yoonu_makk',
                'tags' => json_encode(['Laravel', 'Flutter', 'MySQL', 'REST API']),
                'ordre' => 0,
                'complexite' => 95,
                'type' => 'Mobile + API',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'MonTerrain',
                'description' => 'Plateforme de réservation de terrains de sport avec calendrier interactif, système de paiement et gestion des réservations (confirmation, annulation). Panneau d\'administration pour le suivi des utilisateurs et des créneaux.',
                'image' => 'images/projets/monterrain.png',
                'lien' => 'https://monterrain-02i2.onrender.com',
                'github' => 'https://github.com/papechk/monterrain',
                'tags' => json_encode(['Laravel', 'Breeze', 'FullCalendar', 'Tailwind']),
                'ordre' => 1,
                'complexite' => 80,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'ClassLog',
                'description' => 'Application desktop de gestion scolaire permettant la gestion des classes, enseignants, matières, emplois du temps et affectations. Développée avec C#, WinForms et Entity Framework, connectée à SQL Server.',
                'image' => 'images/projets/gestion-cahier-textes.png',
                'lien' => 'https://github.com/papechk/GestionCahierTexte/releases/tag/v1.0.0',
                'github' => 'https://github.com/papechk/GestionCahierTexte',
                'tags' => json_encode(['C#', '.NET', 'WinForms', 'Entity Framework', 'SQL Server']),
                'ordre' => 5,
                'complexite' => 80,
                'type' => 'Desktop',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
                        [
                'user_id' => $user->id,
                'titre' => 'PapiGPT',
                'description' => 'Application web de génération de lettres et documents à partir de modèles (autorisation, partenariat, financement…). Templates dynamiques, personnalisation avancée et gestion de plusieurs designs de mise en page.',
                'image' => 'images/projets/papigpt.png',
                'lien' => null,
                'github' => 'https://github.com/papechk/papigpt',
                'tags' => json_encode(['Laravel', 'Blade', 'Tailwind', 'PHP']),
                'ordre' => 7,
                'complexite' => 65,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => $user->id,
                'titre' => 'SignalementUrbain',
                'description' => 'Application web permettant de signaler des problèmes urbains via une carte interactive (type Waze). Gestion des catégories, suivi en temps réel et tableau de bord administratif pour le traitement des incidents.',
                'image' => 'images/projets/signalementurbain.png',
                'lien' => 'https://signalementurbain.onrender.com',
                'github' => 'https://github.com/papechk/SignalementUrbain',
                'tags' => json_encode(['Laravel', 'Leaflet.js', 'Tailwind', 'PHP']),
                'ordre' => 4,
                'complexite' => 85,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => $user->id,
                'titre' => 'TaskManager',
                'description' => 'Outil de gestion de tâches avec trois niveaux d\'accès : admin, manager, utilisateur. Chacun voit ses tâches, peut filtrer par priorité ou statut, et assigner du travail aux autres.',
                'image' => 'images/projets/taskmanager.png',
                'lien' => 'https://taskmanager-uvp6.onrender.com',
                'github' => 'https://github.com/papechk/TaskManager',
                'tags' => json_encode(['Laravel', 'Breeze', 'Tailwind', 'Alpine.js']),
                'ordre' => 2,
                'complexite' => 75,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'GStockBoncoin',
                'description' => 'Gestion complète d\'un commerce : stock, produits, ventes, clients, dépenses. Chaque boutique a ses propres données et ses résumés de fin de journée. Le plus gros projet que j\'ai fait en Laravel + Vue.',
                'image' => 'images/projets/gstockboncoin.png',
                'lien' => 'https://gstockboncoin.onrender.com',
                'github' => 'https://github.com/papechk/gStockBoncoin',
                'tags' => json_encode(['Laravel', 'Vue.js', 'Inertia.js', 'Tailwind']),
                'ordre' => 3,
                'complexite' => 90,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => $user->id,
                'titre' => 'SunuTontine',
                'description' => 'Pour gérer les tontines entre amis ou collègues. On crée une tontine, on ajoute les membres, on suit qui a cotisé ou pas sur un calendrier. Le gestionnaire et les participants ont chacun leur vue.',
                'image' => 'images/projets/sunutontine.png',
                'lien' => null,
                'github' => 'https://github.com/papechk/sunuTontine',
                'tags' => json_encode(['Laravel', 'Breeze', 'FullCalendar', 'Tailwind']),
                'ordre' => 6,
                'complexite' => 75,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => $user->id,
                'titre' => 'GestionSalaire',
                'description' => 'Petit outil RH pour calculer et suivre les salaires des employés par département. Rien de fou mais ça fait le job proprement.',
                'image' => 'images/projets/gestionsalaire.png',
                'lien' => 'https://gestionsalaire-2y3h.onrender.com',
                'github' => 'https://github.com/papechk/gestionSalaire',
                'tags' => json_encode(['Laravel', 'Breeze', 'MySQL', 'Tailwind']),
                'ordre' => 8,
                'complexite' => 60,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 40,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Quiz Interactif',
                'description' => 'Quiz en ligne sur Linux, Oracle, Python, Windows Server et l\'admission à Sherbrooke. Les scores sont sauvegardés sur Supabase, et y a des mini-cours pour réviser entre les tentatives.',
                'image' => 'images/projets/quiz-interactif.png',
                'lien' => 'https://pkeinde6.github.io/quiz-app',
                'github' => 'https://github.com/Pkeinde6/quiz-app',
                'tags' => json_encode(['Vue.js', 'Tailwind', 'Supabase']),
                'ordre' => 9,
                'complexite' => 55,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'user_id' => $user->id,
            //     'titre' => 'TestImo',
            //     'description' => 'Site d\'annonces immobilières tout simple. On poste des biens, on les tague, et la page d\'accueil les affiche. L\'admin gère le tout depuis son espace.',
            //     'image' => 'images/projets/testimo.png',
            //     'lien' => null,
            //     'github' => 'https://github.com/papechk/testImo',
            //     'tags' => json_encode(['Laravel', 'Breeze', 'MySQL', 'Tailwind']),
            //     'ordre' => 10,
            //     'complexite' => 55,
            //     'type' => 'Web',
            //     'status' => 'approved',
            //     'progress' => 100,
            //     'approved_at' => now(),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

            [
                'user_id' => $user->id,
                'titre' => 'Projets Python',
                'description' => 'Quelques trucs que j\'ai codés en Python pour m\'entraîner : un jeu de devinette, du chiffrement, un convertisseur, et des exercices sur les listes et fonctions.',
                'image' => 'images/projets/projets-python.png',
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/python-projects',
                'tags' => json_encode(['Python']),
                'ordre' => 12,
                'complexite' => 20,
                'type' => 'Console',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Tic Tac Toe',
                'description' => 'Le morpion classique, fait en deux versions : une en Python dans le terminal et une en Vue.js pour le web. Détecte tout seul qui gagne ou si c\'est match nul.',
                'image' => 'images/projets/tic-tac-toe.png',
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/tic-tac-toe',
                'tags' => json_encode(['Python', 'Vue.js']),
                'ordre' => 13,
                'complexite' => 25,
                'type' => 'Web / Console',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'To-Do List',
                'description' => 'Une to-do list en Vue 3 (Composition API). On ajoute, coche, supprime, filtre par statut — et tout reste sauvegardé dans le localStorage du navigateur.',
                'image' => 'images/projets/todo-list.png',
                'lien' => 'https://pkeinde6.github.io/todo-list/',
                'github' => 'https://github.com/Pkeinde6/todo-list',
                'tags' => json_encode(['Vue.js', 'Vite', 'CSS']),
                'ordre' => 14,
                'complexite' => 25,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Projets .NET',
                'description' => 'Mes projets d\'apprentissage en C# .NET : calculatrices, algorithmes classiques (Armstrong, nombres premiers, Euclide, méthode égyptienne), résolution d\'équations du second degré.',
                'image' => 'images/projets/projets-dotnet.png',
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/dotnet-projects',
                'tags' => json_encode(['C#', '.NET']),
                'ordre' => 15,
                'complexite' => 30,
                'type' => 'Console / Desktop',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Système Bancaire',
                'description' => 'Projet Java pour pratiquer la POO : comptes courants, comptes épargne, dépôts, retraits. Rien de visuel, tout en console, mais la logique objet est propre.',
                'image' => 'images/projets/systeme-bancaire.png',
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/java-banking-system',
                'tags' => json_encode(['Java', 'POO']),
                'ordre' => 16,
                'complexite' => 35,
                'type' => 'Console',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Gestion Scolaire',
                'description' => 'App desktop WinForms pour une école : on inscrit les élèves, on gère les classes, on saisit les notes et ça génère les bulletins. Connecté à SQL Server.',
                'image' => 'images/projets/gestion-scolaire.png',
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/gestionEcole',
                'tags' => json_encode(['C#', '.NET', 'WinForms', 'SQL Server']),
                'ordre' => 17,
                'complexite' => 75,
                'type' => 'Desktop',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Portfolio Dynamique',
                'description' => 'Mon portfolio perso. Animations GSAP au scroll, transitions en plusieurs phases, back-end Laravel avec dashboard, suivi des visites et système de soumission de projets.',
                'image' => 'images/projets/portfolio-dynamique.png',
                'lien' => 'https://cheikh-zqzt.onrender.com',
                'github' => 'https://github.com/papechk/foliolara',
                'tags' => json_encode(['Laravel', 'Tailwind', 'GSAP', 'WebGL']),
                'ordre' => 18,
                'complexite' => 70,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
