<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $user = \App\Models\User::create([
            'nom' => 'Cheikh Keinde',
            'slogan' => 'Développeur Full-Stack',
            'description' => 'Développeur Full-Stack passionné, spécialisé en Laravel, Vue.js, C# .NET et solutions web modernes.',
            'photo' => 'default-avatar.jpg',
            'tel1' => '772756581',
            'tel2' => '+1(438) 465-8983',
            'email' => 'pkeinde6@gmail.com',
            'password' => 'password',
            'adresse' => 'Dakar, Sénégal',
            'poste' => 'Full-Stack Developer',
            'link' => 'https://github.com/papechk',
            'role' => 'superadmin',
        ]);

        \App\Models\Projet::insert([
            [
                'user_id' => $user->id,
                'titre' => 'MonTerrain',
                'description' => 'Plateforme de réservation de terrains de sport avec calendrier FullCalendar, système de paiement, confirmation/annulation des réservations, personnalisation du curseur et panneau d\'administration.',
                'image' => 'images/projets/monterrain.png',
                'lien' => 'https://monterrain-02i2.onrender.com',
                'github' => 'https://github.com/papechk/monterrain',
                'tags' => json_encode(['Laravel', 'Breeze', 'FullCalendar', 'Tailwind']),
                'ordre' => 1,
                'complexite' => 80,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'TaskManager',
                'description' => 'Application de gestion de tâches avec système de rôles (admin, manager, utilisateur), assignation de tâches, filtrage par statut/priorité et tableau de bord par rôle.',
                'image' => 'images/projets/taskmanager.png',
                'lien' => 'https://taskmanager-uvp6.onrender.com',
                'github' => 'https://github.com/papechk/TaskManager',
                'tags' => json_encode(['Laravel', 'Breeze', 'Tailwind', 'Alpine.js']),
                'ordre' => 2,
                'complexite' => 75,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'GStockBoncoin',
                'description' => 'Système de gestion de stock et point de vente : boutiques, catégories, produits, clients, ventes avec lignes de vente, mouvements de stock, dépenses et résumés journaliers.',
                'image' => 'images/projets/gstockboncoin.png',
                'lien' => 'https://gstockboncoin.onrender.com',
                'github' => 'https://github.com/papechk/gStockBoncoin',
                'tags' => json_encode(['Laravel', 'Vue.js', 'Inertia.js', 'Tailwind']),
                'ordre' => 3,
                'complexite' => 90,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'SignalementUrbain',
                'description' => 'Plateforme de signalement urbain avec carte interactive Leaflet style Waze, gestion des catégories de signalements, réservation de terrains, système de paiement et tableau de bord.',
                'image' => 'images/projets/signalementurbain.png',
                'lien' => 'https://signalementurbain.onrender.com',
                'github' => 'https://github.com/papechk/SignalementUrbain',
                'tags' => json_encode(['Laravel', 'Leaflet.js', 'Tailwind', 'PHP']),
                'ordre' => 4,
                'complexite' => 85,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'ClassLog',
                'description' => 'Application desktop WinForms de gestion scolaire : classes, départements, matières, professeurs, responsables, séances, devoirs, emplois du temps et affectations avec Entity Framework.',
                'image' => 'images/projets/gestion-cahier-textes.png',
                'lien' => 'https://github.com/papechk/GestionCahierTexte/releases/tag/v1.0.0',
                'github' => 'https://github.com/papechk/GestionCahierTexte',
                'tags' => json_encode(['C#', '.NET', 'WinForms', 'Entity Framework', 'SQL Server']),
                'ordre' => 5,
                'complexite' => 80,
                'type' => 'Desktop',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'SunuTontine',
                'description' => 'Application de gestion de tontines avec CRUD tontines et membres, suivi des cotisations, calendrier FullCalendar, rôles gestionnaire/participant et tableau de bord par rôle.',
                'image' => 'images/projets/sunutontine.png',
                'lien' => 'https://sunutontine.onrender.com',
                'github' => 'https://github.com/papechk/sunuTontine',
                'tags' => json_encode(['Laravel', 'Breeze', 'FullCalendar', 'Tailwind']),
                'ordre' => 6,
                'complexite' => 75,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'PapiGPT',
                'description' => 'Application de création de lettres et documents avec modèles par catégorie (Autorisation, Collaboration, Financement, Partenariat, Invitation, Notification, Recommandation…), 5 designs, rédaction libre et gestion de templates.',
                'image' => 'images/projets/papigpt.png',
                'lien' => 'https://papigpt.onrender.com',
                'github' => 'https://github.com/papechk/papigpt',
                'tags' => json_encode(['Laravel', 'Blade', 'Tailwind', 'PHP']),
                'ordre' => 7,
                'complexite' => 65,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'GestionSalaire',
                'description' => 'Application de gestion des salaires avec départements, employés, calcul et suivi des salaires, authentification et tableau de bord.',
                'image' => 'images/projets/gestionsalaire.png',
                'lien' => 'https://gestionsalaire.onrender.com',
                'github' => 'https://github.com/papechk/gestionSalaire',
                'tags' => json_encode(['Laravel', 'Breeze', 'MySQL', 'Tailwind']),
                'ordre' => 8,
                'complexite' => 60,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Quiz Interactif',
                'description' => 'Application de quiz interactive avec catégories Linux, Oracle, Python, Windows Server et Admission Sherbrooke. Suivi des scores via Supabase, mini-cours intégrés et interface responsive.',
                'image' => 'images/projets/quiz-interactif.png',
                'lien' => 'https://pkeinde6.github.io/quiz-app',
                'github' => 'https://github.com/Pkeinde6/quiz-app',
                'tags' => json_encode(['Vue.js', 'Tailwind', 'Supabase']),
                'ordre' => 9,
                'complexite' => 55,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'TestImo',
                'description' => 'Application d\'annonces immobilières avec gestion de propriétés, système de tags, panneau d\'administration et page d\'accueil vitrine.',
                'image' => 'images/projets/testimo.png',
                'lien' => 'https://testimo.onrender.com',
                'github' => 'https://github.com/papechk/testImo',
                'tags' => json_encode(['Laravel', 'Breeze', 'MySQL', 'Tailwind']),
                'ordre' => 10,
                'complexite' => 55,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Star Group',
                'description' => 'Site vitrine multi-pages pour l\'entreprise Star Group avec accueil, services, à propos et contact.',
                'image' => 'images/projets/star-group.png',
                'lien' => 'https://star-groupe.com',
                'github' => 'https://github.com/Pkeinde6/Star-group',
                'tags' => json_encode(['PHP', 'CSS', 'JavaScript']),
                'ordre' => 11,
                'complexite' => 35,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Projets Python',
                'description' => 'Exercices et projets Python : jeu de devinette, cryptographie, convertisseur, manipulation de listes et fonctions.',
                'image' => 'images/projets/projets-python.png',
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/python-projects',
                'tags' => json_encode(['Python']),
                'ordre' => 12,
                'complexite' => 20,
                'type' => 'Console',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Tic Tac Toe',
                'description' => 'Jeu de morpion classique développé en Python (CLI) et en Vue.js (web), avec détection automatique des victoires et matchs nuls.',
                'image' => 'images/projets/tic-tac-toe.png',
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/tic-tac-toe',
                'tags' => json_encode(['Python', 'Vue.js']),
                'ordre' => 13,
                'complexite' => 25,
                'type' => 'Web / Console',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'To-Do List',
                'description' => 'Application de gestion de tâches avec Vue 3 Composition API : ajout, suppression, filtrage (toutes/actives/terminées) et persistance via localStorage.',
                'image' => 'images/projets/todo-list.png',
                'lien' => 'https://pkeinde6.github.io/todo-list/',
                'github' => 'https://github.com/Pkeinde6/todo-list',
                'tags' => json_encode(['Vue.js', 'Vite', 'CSS']),
                'ordre' => 14,
                'complexite' => 25,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Projets .NET',
                'description' => 'Collection de projets console et desktop en C# .NET : calculatrices, algorithmes (Armstrong, nombres premiers, Euclide, méthode égyptienne), équations du second degré.',
                'image' => 'images/projets/projets-dotnet.png',
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/dotnet-projects',
                'tags' => json_encode(['C#', '.NET']),
                'ordre' => 15,
                'complexite' => 30,
                'type' => 'Console / Desktop',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Système Bancaire',
                'description' => 'Système bancaire orienté objet en Java avec gestion de comptes courants, comptes épargne, dépôts et retraits.',
                'image' => 'images/projets/systeme-bancaire.png',
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/java-banking-system',
                'tags' => json_encode(['Java', 'POO']),
                'ordre' => 16,
                'complexite' => 35,
                'type' => 'Console',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Gestion Scolaire',
                'description' => 'Application desktop de gestion d\'établissement scolaire : inscription élèves, gestion des classes, saisie de notes, emplois du temps et génération de bulletins.',
                'image' => 'images/projets/gestion-scolaire.png',
                'lien' => null,
                'github' => 'https://github.com/Pkeinde6/gestionEcole',
                'tags' => json_encode(['C#', '.NET', 'WinForms', 'SQL Server']),
                'ordre' => 17,
                'complexite' => 75,
                'type' => 'Desktop',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'titre' => 'Portfolio Dynamique',
                'description' => 'Site portfolio avec animations GSAP avancées, scroll-driven transitions en 9 phases, effet WebGL sur images et gestion de contenu Laravel.',
                'image' => 'images/projets/portfolio-dynamique.png',
                'lien' => 'https://cheikh-p6j9.onrender.com',
                'github' => 'https://github.com/papechk/foliolara',
                'tags' => json_encode(['Laravel', 'Tailwind', 'GSAP', 'WebGL']),
                'ordre' => 18,
                'complexite' => 70,
                'type' => 'Web',
                'status' => 'approved',
                'progress' => 100,
                'approved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
