services:
  - type: web
    name: foliolara
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: FolioLara
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SUPABASE_URL
        value: https://npfuctogigxiivvqtuhs.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wZnVjdG9naWd4aWl2dnF0dWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NDAxNzYsImV4cCI6MjA4OTUxNjE3Nn0.jVGc0tKJRkRsAVB11F-WQBby4FCDfly6N_7k5nLPgjI
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: FolioLara
